pipeline {
    agent any
	tools {
            terraform 'terraform'
        }
    stages {
	stage('Git Checkout'){
            steps{
            git branch: 'main', url: 'https://github.com/ashokdas14/simple-node-js-react-npm-app.git'
            }
        }
	stage('Build') {
            steps {
                sh 'npm install'
				sh 'chmod 777 ./jenkins/scripts/test.sh'
				sh 'chmod 777 ./jenkins/scripts/deliver.sh'
				sh 'chmod 777 ./jenkins/scripts/kill.sh'
            }
        }	
	stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
	stage('Terraform'){
            steps{
            sh 'terraform init'
	    sh 'terraform plan'
	    sh 'terraform validate'
            }
        }
	stage('Terraform Approval'){
            steps{
            input "Deploy Infra?"
            }
        }
        stage('Terraform Apply'){
            steps{
            sh 'terraform apply --auto-approve';
            }
        }	
	    
    stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
