pipeline {
    agent any
    stages {
		stage('Git Checkout'){
            steps{
            git branch: 'main', url: 'https://github.com/ashokdas14/simple-node-js-react-npm-app.git'
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
	stage('permission') {
	    steps {
		    sh 'chmod 777 jenkins'
	    }
    }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
